# Clustering Exploration

### Import Dataset

In [13]:
import pandas as pd 
import numpy as np
np.seterr(over='ignore')

# from sklearn import datasets

# # import some data to play with
# iris = datasets.load_iris()
# iris_features = iris.data
# iris_labels = iris.target
# # print(iris_data)

# iris_features = pd.DataFrame(data=iris_features)


df = pd.read_csv('dataset/tennis.csv')
df = df.drop('day', axis = 1)

tennis_features = df.drop('play', axis = 1)
tennis_labels = df.drop(list(features), axis = 1)

df = pd.read_csv('dataset/iris.csv')

df.head(5)

# tennis_features = df.drop('variety', axis = 1)
# tennis_labels = df.drop(list(features), axis = 1)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [12]:
iris_features.head(5)
# tennis_features.head(5)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

### One Hot Encoder 

Konversi data kategorik menjadi sparse

In [3]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

features = pd.get_dummies(features)
features.head()

outlook_Overcast  outlook_Rain  outlook_Sunny  temp_Cool  temp_Hot  \
0                 0             0              1          0         1   
1                 0             0              1          0         1   
2                 1             0              0          0         1   
3                 0             1              0          0         0   
4                 0             1              0          1         0   

   temp_Mild  humidity_High  humidity_Normal  wind_Strong  wind_Weak  
0          0              1                0            0          1  
1          0              1                0            1          0  
2          0              1                0            0          1  
3          1              1                0            0          1  
4          0              0                1            0          1

### K-Means

In [4]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=2, random_state=0)

kmeans.fit(features)
result = kmeans.predict(features)

print(result)

[1 1 1 1 0 0 0 1 0 0 0 1 0 1]


### Agglomerative Clustering

In [5]:
from sklearn.cluster import AgglomerativeClustering

clustering = AgglomerativeClustering()
result = clustering.fit_predict(features)

print(result)

[0 0 0 0 1 1 1 0 1 1 0 0 0 0]


### DBSCAN

In [6]:
from sklearn.cluster import DBSCAN

clustering = DBSCAN(eps=4, min_samples=2)
result = clustering.fit_predict(features)

print(result)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0]


### Gaussian Mixture

In [7]:
from sklearn.mixture import GaussianMixture

model = GaussianMixture()
model.fit(features)
result = model.predict(features)

print(result)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0]


### K-Medoids

In [8]:
from pyclustering.cluster.kmedoids import kmedoids
from pyclustering.utils.metric import distance_metric, type_metric

list_features = []
for i in features.index:
    list_features.append(np.array(features.iloc[[i]])[0])
    
metric = distance_metric(type_metric.MINKOWSKI, degree = 4)
# metric = distance_metric(type_metric.CHEBYSHEV)

# set initial medoids
initial_medoids = [1, 6]

# create instance of K-Medoids algorithm
kmedoids_instance = kmedoids(list_features, initial_medoids, metric = metric)

# run cluster analysis and obtain results
kmedoids_instance.process();
clusters = kmedoids_instance.get_clusters()

# show allocated clusters
print(clusters)

[[7, 0, 1, 2, 3, 10, 11, 13], [4, 5, 6, 8, 9, 12]]


### MST

In [50]:
import matplotlib.pyplot as plt

from mst_clustering import MSTClustering
model = MSTClustering(cutoff_scale=1.414214, approximate=False)
labels = model.fit_predict(features)

print(labels)

[0 0 0 0 0 0 0 0 0 0 1 0 0 0]


### Grid Clustering

In [66]:
from grid_based_clustering.clusterData import clusterTwoColumns

# print(features[1])

attributes = features.iloc[[1]]
min_den = 10
gridSize = len(attributes)

# Execute clustering strategy.
for i in range(len(attributes)-1):
    for j in range(i+1, len(attributes)-1):
        clusterTwoColumns(attributes[i], attributes[j], features, min_den, gridSize)

# print(features)
# print(attributes)